const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const db = require('../db');
const { findFreePort } = require('../utils/ports');
const { downloadServerJar } = require('./mojang');
const { downloadBedrockServer, generateBedrockServerProperties } = require('./bedrock');

const SERVERS_DIR = path.join(__dirname, '..', '..', 'data', 'servers');

// Ensure servers directory exists
if (!fs.existsSync(SERVERS_DIR)) {
    fs.mkdirSync(SERVERS_DIR, { recursive: true });
}

/**
 * Generate default Java server.properties content.
 */
function generateServerProperties(port, name) {
    return [
        `# Minecraft server properties`,
        `# Generated by MC Server Manager`,
        `server-port=${port}`,
        `motd=${name}`,
        `level-name=world`,
        `gamemode=survival`,
        `difficulty=normal`,
        `max-players=20`,
        `view-distance=10`,
        `spawn-protection=16`,
        `online-mode=true`,
        `enable-command-block=false`,
        `pvp=true`,
        `allow-flight=false`,
        `white-list=false`,
        `spawn-npcs=true`,
        `spawn-animals=true`,
        `spawn-monsters=true`,
        `generate-structures=true`,
        `level-seed=`,
        ``
    ].join('\n');
}

/**
 * Create a new Minecraft server (Java or Bedrock edition).
 * @param {string} name - Server name
 * @param {string} version - Game version
 * @param {string} type - Software type: vanilla | paper | fabric | forge (Java only)
 * @param {string} edition - Edition: 'java' | 'bedrock'
 * @param {function} onProgress - Progress callback
 */
async function createServer(name, version, type = 'vanilla', edition = 'java', onProgress) {
    const id = crypto.randomUUID();
    const serverDir = path.join(SERVERS_DIR, id);

    // 1. Determine starting port
    const existingPorts = db.all('SELECT port FROM servers').map((r) => r.port);

    let defaultPort;
    if (edition === 'bedrock') {
        // Bedrock default: 19132 (UDP)
        defaultPort = 19132;
        // Increment past existing bedrock ports
        while (existingPorts.includes(defaultPort)) defaultPort++;
    } else {
        // Java default: 25565 (TCP)
        defaultPort = 25565;
        while (existingPorts.includes(defaultPort)) defaultPort++;
    }

    const port = edition === 'bedrock'
        ? defaultPort  // UDP ports can't be checked with TCP findFreePort
        : await findFreePort(defaultPort);

    // 2. Create server directory
    fs.mkdirSync(serverDir, { recursive: true });

    if (edition === 'java') {
        if (type === 'paper') {
            fs.mkdirSync(path.join(serverDir, 'plugins'), { recursive: true });
        } else if (type === 'fabric' || type === 'forge') {
            fs.mkdirSync(path.join(serverDir, 'mods'), { recursive: true });
        }
    }

    // 3. Download server files
    if (onProgress) onProgress({ stage: 'downloading', percent: 0 });

    if (edition === 'bedrock') {
        await downloadBedrockServer(version, serverDir, (percent) => {
            if (onProgress) onProgress({ stage: 'downloading', percent });
        });

        // Write Bedrock server.properties
        fs.writeFileSync(
            path.join(serverDir, 'server.properties'),
            generateBedrockServerProperties(port, name)
        );

    } else {
        // Java edition
        await downloadServerJar(version, serverDir, type, (percent) => {
            if (onProgress) onProgress({ stage: 'downloading', percent });
        });

        // Write eula.txt (required by Java servers)
        fs.writeFileSync(path.join(serverDir, 'eula.txt'), 'eula=true\n');

        // Write server.properties
        fs.writeFileSync(
            path.join(serverDir, 'server.properties'),
            generateServerProperties(port, name)
        );
    }

    // 4. Insert into database
    db.run(
        `INSERT INTO servers (id, name, version, type, edition, port, path, status, createdAt)
     VALUES (?, ?, ?, ?, ?, ?, ?, 'offline', datetime('now'))`,
        [id, name, version, type, edition, port, serverDir]
    );

    if (onProgress) onProgress({ stage: 'done', percent: 100 });

    return getServer(id);
}

/**
 * Get a server by ID.
 */
function getServer(id) {
    return db.get('SELECT * FROM servers WHERE id = ?', [id]);
}

/**
 * Get all servers.
 */
function getAllServers() {
    return db.all('SELECT * FROM servers ORDER BY createdAt DESC');
}

/**
 * Update server status.
 */
function updateStatus(id, status) {
    db.run('UPDATE servers SET status = ? WHERE id = ?', [status, id]);
}

/**
 * Delete a server and its files.
 */
function deleteServer(id) {
    const server = getServer(id);
    if (server) {
        db.run('DELETE FROM servers WHERE id = ?', [id]);
        if (fs.existsSync(server.path)) {
            fs.rmSync(server.path, { recursive: true, force: true });
        }
    }
}

module.exports = {
    createServer,
    getServer,
    getAllServers,
    updateStatus,
    deleteServer,
    SERVERS_DIR
};
